---
resource_types:

- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest

- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:

- name: scdf-demo
  type: git
  source:
    uri: https://github.com/sharadg/twitter-scdf-demo
    branch: master

- name: pcf-env
  type: cf-cli-resource
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASSWORD}}
    skip_cert_check: true
    org: {{CF_ORG}}
    space: {{CF_SPACE}}

- name: pcf-env-params
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASSWORD}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}
    skip_cert_check: true

cf-params: &cf-params
  CF_API: {{CF_API}}
  CF_SKIP_SSL: true
  CF_USER: {{CF_USER}}
  CF_PASSWORD: {{CF_PASSWORD}}
  CF_ORG: {{CF_ORG}}
  CF_SPACE: {{CF_SPACE}}

jobs:

- name: deploy-scdf-demo
  plan:
  - aggregate:
    - get: scdf-demo
  - put: cf-create-services
    resource: pcf-env
    params:
      commands:
      - command: create-service
        org: {{CF_ORG}}
        space: {{CF_SPACE}}
        service: {{SCDF_SERVICE_NAME}}
        plan: {{SCDF_SERVICE_PLAN}}
        service_instance: dataflow-server
  - task: build-bubble
    file: scdf-demo/ci/build-bubble.yml
  - task: run-register-apps
    file: scdf-demo/ci/run-register-apps.yml
    params:
      <<: *cf-params
  - put: cf-push
    resource: pcf-env
    params:
      command: push
      app_name: bubble-chart
      manifest: scdf-demo/ci/bubble-manifest.yml
      no_start: true

- name: tear-down-scdf-demo
  plan:
  - put: cf-delete-everything
    resource: pcf-env
    params:
      commands:
      - command: delete
        app_name: bubble-chart
        delete_mapped_routes: true
      - command: delete-service
        service_instance: dataflow-server
